FROM datadog/agent:7.44.1

ENV DD_AUTOCONFIG_FROM_ENVIRONMENT=true

ENV DD_APM_ENABLED=true
ENV DD_LOGS_STDOUT=yes

ENV NON_LOCAL_TRAFFIC=true
ENV DD_APM_NON_LOCAL_TRAFFIC=true
ENV DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
ENV DD_PROCESS_AGENT_ENABLED=true

ARG DD_API_KEY
ARG DD_SITE
ARG DD_HOSTNAME
